services:
  wordpress:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mysql
    volumes:
      - ./plugin:/var/www/html/wp-content/plugins/plugin

  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress

volumes:
  db_data:
