
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_AUTO_UPDATE_CORE', false);
        define('AUTOMATIC_UPDATER_DISABLED', true);
    env_file:
      - wp-config.env
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./plugin:/var/www/html/wp-content/plugins/media-player-plugin
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_MAX_CONNECTIONS: 1000
    command: --default-authentication-plugin=mysql_native_password --max_connections=1000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wordpress", "-pwordpress_password"]
      timeout: 5s
      retries: 10
      interval: 5s
      start_period: 40s

volumes:
  db_data:
